# %% [markdown]
# # Topic 5: OpenAPI Specification & API Documentation Playground
# In this playground, you will learn how to customize and enrich your API's documentation.
# We will inspect how FastAPI translates Python code, types, and Pydantic models
# into a standard OpenAPI JSON specification.
#
# **How to use this:**
# 1. Open this file in VS Code.
# 2. Click **"Run Cell"** above each code block.

# %%
# 1. IMPORT LIBRARIES
from fastapi import FastAPI, status, Query, Path
from fastapi.testclient import TestClient
from pydantic import BaseModel, Field
import json

# %% [markdown]
# ## Enriching the FastAPI Application Metadata
# We can customize the main API title, description, version, and even the URL where
# the Swagger UI is hosted (default is `/docs`).

# %%
# 2. APPLICATION METADATA
app = FastAPI(
    title="Elite E-Commerce Catalog Service",
    description="""
    Welcome to the Elite E-Commerce Catalog Service API.
    This service allows you to manage product listings, categories, and inventory.
    
    ## Features
    * Create, read, update, and delete catalog products.
    * Filter products by category and price.
    * Automatic validation of all inputs.
    """,
    version="1.4.2",
    contact={
        "name": "API Support Team",
        "email": "support@elitecorp.com",
    },
    license_info={
        "name": "Apache 2.0",
        "url": "https://www.apache.org/licenses/LICENSE-2.0.html",
    },
    docs_url="/dev-portal/swagger",  # Custom Swagger UI URL
    redoc_url="/dev-portal/redoc"     # Custom Redoc URL
)

# %% [markdown]
# ## Documenting Request Schemas with Pydantic
# By using Pydantic's `Field` class, we can attach descriptions, validation constraints,
# and placeholder examples. These examples are rendered directly in the Swagger UI,
# allowing developers to click "Try it out" and instantly have a valid payload ready.

# %%
# 3. SCHEMA DOCUMENTATION
class ProductCreate(BaseModel):
    name: str = Field(
        ..., 
        min_length=2, 
        max_length=100, 
        description="The official name of the product as displayed in the store catalog.",
        examples=["Logitech MX Master 3S"]
    )
    price: float = Field(
        ..., 
        gt=0, 
        description="The retail unit price in USD. Must be greater than 0.",
        examples=[99.99]
    )
    category: str = Field(
        ..., 
        min_length=2, 
        description="The department or category classification.",
        examples=["Electronics"]
    )

class ProductResponse(BaseModel):
    id: int = Field(..., description="The unique auto-incremented database identifier.")
    name: str
    price: float
    category: str

# %% [markdown]
# ## Documenting Endpoints
# We use decorator parameters (`summary`, `description`, `response_description`, `tags`)
# and helper functions like `Query` and `Path` to document individual parameters.

# %%
# 4. ENRICHED ROUTE DEFINITIONS

@app.post(
    "/api/v1/products",
    response_model=ProductResponse,
    status_code=status.HTTP_201_CREATED,
    tags=["Product Management"],
    summary="Add a new product to the catalog",
    response_description="Returns the created product details, including its assigned database ID."
)
def create_product(product_in: ProductCreate):
    """
    Register a new product in the system database.
    
    - **name**: Must be unique
    - **price**: Must be a positive decimal
    - **category**: String matching an active category
    """
    # In-memory mock save
    created_product = {
        "id": 101,
        "name": product_in.name,
        "price": product_in.price,
        "category": product_in.category
    }
    return created_product

@app.get(
    "/api/v1/products/{product_id}",
    response_model=ProductResponse,
    tags=["Product Catalog"],
    summary="Retrieve a specific product by ID",
    response_description="Returns the requested product record."
)
def get_product(
    product_id: int = Path(
        ..., 
        description="The unique ID of the product to fetch", 
        ge=1, 
        examples=[101]
    )
):
    if product_id == 101:
        return {"id": 101, "name": "Logitech MX Master 3S", "price": 99.99, "category": "Electronics"}
    raise HTTPException(status_code=404, detail="Product not found")

# %%
# 5. INITIALIZE TEST CLIENT
client = TestClient(app)

# %% [markdown]
# ### Inspecting the Autogenerated OpenAPI JSON Schema
# Under the hood, FastAPI serves the OpenAPI JSON at `/openapi.json`. 
# Let's fetch it using our `TestClient` and inspect its structure.
# You will see all our custom descriptions, titles, versions, and examples embedded inside it!

# %%
response = client.get("/openapi.json")

print(f"Status Code: {response.status_code}")
openapi_spec = response.json()

# Let's print the general info section of the spec
print("\n--- General API Info ---")
print(json.dumps(openapi_spec["info"], indent=2))

# Let's print the documentation of our POST /api/v1/products endpoint
print("\n--- POST /api/v1/products Spec ---")
print(json.dumps(openapi_spec["paths"]["/api/v1/products"]["post"], indent=2))
